### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by jiripudil** [Kdyby/RequestStack#1]
Hi there, would you care to tag a new release? The [late two commits](https://github.com/Kdyby/RequestStack/compare/v0.3.0...master) incidentally fix compatibility with PHP 7.2 by removing `extends Nette\Object` :wink:

**Comment by enumag** [comment]
I added PHP 7.2 to Travis to see if everything works but there are some failures. If you can send a PR with a fix, I'll tag new version then.

https://travis-ci.org/Kdyby/RequestStack

**Comment by jiripudil** [comment]
Seems like it's just nette/tester in need of update because of [this](https://github.com/nette/tester/commit/83317fa991ab9cd2bb9610129fc75c53c2c417b6). I'll take a look at it tomorrow.

**Comment by jiripudil** [comment]
Thanks @enumag, closing :)
